// Pre-computed synthetic scenario results. Generated by a private build tool; no calculation source ships with this page.
const SCW_DATA = {
 "scenarios": {
  "baseline": {
   "label": "Baseline (no disruption)",
   "totals": {
    "expedite_spend": 0.0,
    "baseline_loss": 0.0,
    "residual_loss": 0.0,
    "loss_avoided": 0.0,
    "net_benefit": 0.0,
    "accepted_components": []
   },
   "components_short": 0,
   "components_total": 24,
   "products": [
    {
     "name": "Brake caliper assembly",
     "weeks_stopped": 0,
     "first_stop": "",
     "margin_at_risk": 0.0,
     "penalty": 0.0,
     "blockers": ""
    },
    {
     "name": "Clutch housing",
     "weeks_stopped": 0,
     "first_stop": "",
     "margin_at_risk": 0.0,
     "penalty": 0.0,
     "blockers": ""
    },
    {
     "name": "Alternator unit",
     "weeks_stopped": 0,
     "first_stop": "",
     "margin_at_risk": 0.0,
     "penalty": 0.0,
     "blockers": ""
    },
    {
     "name": "EGR valve module",
     "weeks_stopped": 0,
     "first_stop": "",
     "margin_at_risk": 0.0,
     "penalty": 0.0,
     "blockers": ""
    },
    {
     "name": "Turbo actuator",
     "weeks_stopped": 0,
     "first_stop": "",
     "margin_at_risk": 0.0,
     "penalty": 0.0,
     "blockers": ""
    },
    {
     "name": "Fuel rail assembly",
     "weeks_stopped": 0,
     "first_stop": "",
     "margin_at_risk": 0.0,
     "penalty": 0.0,
     "blockers": ""
    },
    {
     "name": "Steering knuckle set",
     "weeks_stopped": 0,
     "first_stop": "",
     "margin_at_risk": 0.0,
     "penalty": 0.0,
     "blockers": ""
    },
    {
     "name": "Wiring harness (engine)",
     "weeks_stopped": 0,
     "first_stop": "",
     "margin_at_risk": 0.0,
     "penalty": 0.0,
     "blockers": ""
    },
    {
     "name": "ECU bracket module",
     "weeks_stopped": 0,
     "first_stop": "",
     "margin_at_risk": 0.0,
     "penalty": 0.0,
     "blockers": ""
    },
    {
     "name": "Oil pump assembly",
     "weeks_stopped": 0,
     "first_stop": "",
     "margin_at_risk": 0.0,
     "penalty": 0.0,
     "blockers": ""
    }
   ],
   "plan": [],
   "customers": []
  },
  "port_congestion": {
   "label": "Port congestion (+21d at Nhava Sheva)",
   "totals": {
    "expedite_spend": 2362455.8,
    "baseline_loss": 25980490.42,
    "residual_loss": 12099417.42,
    "loss_avoided": 13881073.0,
    "net_benefit": 11518617.2,
    "accepted_components": [
     "Turbo cartridge core"
    ]
   },
   "components_short": 11,
   "components_total": 24,
   "products": [
    {
     "name": "Brake caliper assembly",
     "weeks_stopped": 11,
     "first_stop": "2026-09-14",
     "margin_at_risk": 3603600.0,
     "penalty": 480480.0,
     "blockers": "C006, C018"
    },
    {
     "name": "Turbo actuator",
     "weeks_stopped": 11,
     "first_stop": "2026-09-14",
     "margin_at_risk": 3110250.0,
     "penalty": 286915.2,
     "blockers": "C006, C010"
    },
    {
     "name": "Oil pump assembly",
     "weeks_stopped": 11,
     "first_stop": "2026-09-14",
     "margin_at_risk": 2976600.0,
     "penalty": 239438.43,
     "blockers": "C005, C007, C012, C024"
    },
    {
     "name": "Wiring harness (engine)",
     "weeks_stopped": 11,
     "first_stop": "2026-09-14",
     "margin_at_risk": 2885300.0,
     "penalty": 239442.99,
     "blockers": "C018, C024"
    },
    {
     "name": "Steering knuckle set",
     "weeks_stopped": 11,
     "first_stop": "2026-09-14",
     "margin_at_risk": 2772000.0,
     "penalty": 318174.78,
     "blockers": "C005, C011, C023"
    },
    {
     "name": "Fuel rail assembly",
     "weeks_stopped": 11,
     "first_stop": "2026-09-14",
     "margin_at_risk": 2618000.0,
     "penalty": 161453.93,
     "blockers": "C011, C023, C024"
    },
    {
     "name": "Alternator unit",
     "weeks_stopped": 8,
     "first_stop": "2026-09-14",
     "margin_at_risk": 2585600.0,
     "penalty": 252588.88,
     "blockers": "C010"
    },
    {
     "name": "EGR valve module",
     "weeks_stopped": 11,
     "first_stop": "2026-09-14",
     "margin_at_risk": 1630200.0,
     "penalty": 176278.96,
     "blockers": "C011, C018, C022, C023, C024"
    },
    {
     "name": "ECU bracket module",
     "weeks_stopped": 11,
     "first_stop": "2026-09-14",
     "margin_at_risk": 1534500.0,
     "penalty": 109667.25,
     "blockers": "C006, C007, C009"
    },
    {
     "name": "Clutch housing",
     "weeks_stopped": 0,
     "first_stop": "",
     "margin_at_risk": 0.0,
     "penalty": 0.0,
     "blockers": ""
    }
   ],
   "plan": [
    {
     "component": "Precision piston (import)",
     "option": "alt_supplier",
     "detail": "emergency order 100 units from Schwarzwald Metall (air, 9d lead)",
     "cost": 33900.0,
     "arrival": "2026-09-10"
    },
    {
     "component": "Turbo cartridge core",
     "option": "accept",
     "detail": "no expedite: absorb lost margin and customer penalties",
     "cost": 4288678.35,
     "arrival": ""
    },
    {
     "component": "Actuator gearset",
     "option": "alt_supplier",
     "detail": "emergency order 1848 units from Schwarzwald Metall (air, 9d lead)",
     "cost": 728112.0,
     "arrival": "2026-09-10"
    },
    {
     "component": "Position sensor IC",
     "option": "alt_supplier",
     "detail": "emergency order 1948 units from Han River Components (sea, 33d lead)",
     "cost": 132853.6,
     "arrival": "2026-10-04"
    },
    {
     "component": "Copper winding set",
     "option": "alt_supplier",
     "detail": "emergency order 3848 units from Han River Components (sea, 33d lead)",
     "cost": 330158.4,
     "arrival": "2026-10-04"
    },
    {
     "component": "Injector seat insert",
     "option": "alt_supplier",
     "detail": "emergency order 2790 units from Schwarzwald Metall (air, 9d lead)",
     "cost": 432450.0,
     "arrival": "2026-09-10"
    },
    {
     "component": "Solenoid coil",
     "option": "alt_supplier",
     "detail": "emergency order 760 units from Han River Components (sea, 33d lead)",
     "cost": 38456.0,
     "arrival": "2026-10-04"
    },
    {
     "component": "Harness connector set",
     "option": "alt_supplier",
     "detail": "emergency order 1172 units from Han River Components (sea, 33d lead)",
     "cost": 30940.8,
     "arrival": "2026-10-04"
    },
    {
     "component": "Valve stem (import)",
     "option": "alt_supplier",
     "detail": "emergency order 434 units from Schwarzwald Metall (air, 9d lead)",
     "cost": 49693.0,
     "arrival": "2026-09-10"
    },
    {
     "component": "Rotor lamination stack",
     "option": "alt_supplier",
     "detail": "emergency order 2892 units from Han River Components (sea, 33d lead)",
     "cost": 286308.0,
     "arrival": "2026-10-04"
    },
    {
     "component": "Oil seal (single-source)",
     "option": "air_uplift",
     "detail": "fly 24800 units currently stuck in sea freight",
     "cost": 299584.0,
     "arrival": "2026-09-08"
    }
   ],
   "customers": [
    {
     "customer": "Deccan Trucks",
     "product": "Turbo actuator",
     "strategic": true,
     "weeks": 11,
     "revenue_at_risk": 12835680.0,
     "penalty": 256713.6
    },
    {
     "customer": "Bharat Motors",
     "product": "Brake caliper assembly",
     "strategic": true,
     "weeks": 11,
     "revenue_at_risk": 12684672.0,
     "penalty": 253693.44
    },
    {
     "customer": "Volt EV Systems",
     "product": "Brake caliper assembly",
     "strategic": true,
     "weeks": 11,
     "revenue_at_risk": 11339328.0,
     "penalty": 226786.56
    },
    {
     "customer": "Sunrise Tractors",
     "product": "Oil pump assembly",
     "strategic": false,
     "weeks": 11,
     "revenue_at_risk": 10173438.0,
     "penalty": 50867.19
    },
    {
     "customer": "Apex Two-Wheelers",
     "product": "Wiring harness (engine)",
     "strategic": false,
     "weeks": 11,
     "revenue_at_risk": 9982467.0,
     "penalty": 49912.34
    },
    {
     "customer": "Deccan Trucks",
     "product": "Wiring harness (engine)",
     "strategic": true,
     "weeks": 11,
     "revenue_at_risk": 9476533.0,
     "penalty": 189530.66
    },
    {
     "customer": "Bharat Motors",
     "product": "Oil pump assembly",
     "strategic": true,
     "weeks": 11,
     "revenue_at_risk": 9428562.0,
     "penalty": 188571.24
    },
    {
     "customer": "Sunrise Tractors",
     "product": "Fuel rail assembly",
     "strategic": false,
     "weeks": 11,
     "revenue_at_risk": 8841734.0,
     "penalty": 44208.67
    }
   ]
  },
  "foundry_fire": {
   "label": "Foundry fire (Tunga Castings, 4 weeks)",
   "totals": {
    "expedite_spend": 3784930.2,
    "baseline_loss": 23629597.99,
    "residual_loss": 3287604.65,
    "loss_avoided": 20341993.34,
    "net_benefit": 16557063.14,
    "accepted_components": []
   },
   "components_short": 5,
   "components_total": 24,
   "products": [
    {
     "name": "Brake caliper assembly",
     "weeks_stopped": 12,
     "first_stop": "2026-09-07",
     "margin_at_risk": 3931200.0,
     "penalty": 524160.0,
     "blockers": "C001"
    },
    {
     "name": "Clutch housing",
     "weeks_stopped": 11,
     "first_stop": "2026-09-14",
     "margin_at_risk": 3512300.0,
     "penalty": 307524.03,
     "blockers": "C002, C020"
    },
    {
     "name": "Turbo actuator",
     "weeks_stopped": 12,
     "first_stop": "2026-09-07",
     "margin_at_risk": 3393000.0,
     "penalty": 312998.4,
     "blockers": "C003"
    },
    {
     "name": "Oil pump assembly",
     "weeks_stopped": 12,
     "first_stop": "2026-09-07",
     "margin_at_risk": 3247200.0,
     "penalty": 261205.56,
     "blockers": "C001, C004"
    },
    {
     "name": "Steering knuckle set",
     "weeks_stopped": 12,
     "first_stop": "2026-09-07",
     "margin_at_risk": 3024000.0,
     "penalty": 347099.76,
     "blockers": "C003"
    },
    {
     "name": "Wiring harness (engine)",
     "weeks_stopped": 11,
     "first_stop": "2026-09-14",
     "margin_at_risk": 2885300.0,
     "penalty": 239442.99,
     "blockers": "C004"
    },
    {
     "name": "ECU bracket module",
     "weeks_stopped": 11,
     "first_stop": "2026-09-14",
     "margin_at_risk": 1534500.0,
     "penalty": 109667.25,
     "blockers": "C002, C020"
    },
    {
     "name": "Fuel rail assembly",
     "weeks_stopped": 0,
     "first_stop": "",
     "margin_at_risk": 0.0,
     "penalty": 0.0,
     "blockers": ""
    },
    {
     "name": "Alternator unit",
     "weeks_stopped": 0,
     "first_stop": "",
     "margin_at_risk": 0.0,
     "penalty": 0.0,
     "blockers": ""
    },
    {
     "name": "EGR valve module",
     "weeks_stopped": 0,
     "first_stop": "",
     "margin_at_risk": 0.0,
     "penalty": 0.0,
     "blockers": ""
    }
   ],
   "plan": [
    {
     "component": "Grey-iron caliper casting",
     "option": "alt_supplier",
     "detail": "emergency order 5752 units from Hemavati Foundries (road, 21d lead)",
     "cost": 807580.8,
     "arrival": "2026-09-22"
    },
    {
     "component": "Clutch housing casting",
     "option": "alt_supplier",
     "detail": "emergency order 6002 units from Hemavati Foundries (road, 21d lead)",
     "cost": 1242414.0,
     "arrival": "2026-09-22"
    },
    {
     "component": "Knuckle forging blank",
     "option": "alt_supplier",
     "detail": "emergency order 5522 units from Hemavati Foundries (road, 21d lead)",
     "cost": 934322.4,
     "arrival": "2026-09-22"
    },
    {
     "component": "Pump body casting",
     "option": "alt_supplier",
     "detail": "emergency order 5625 units from Hemavati Foundries (road, 21d lead)",
     "cost": 617625.0,
     "arrival": "2026-09-22"
    },
    {
     "component": "Aluminium end cover",
     "option": "alt_supplier",
     "detail": "emergency order 2990 units from Hemavati Foundries (road, 21d lead)",
     "cost": 182988.0,
     "arrival": "2026-09-22"
    }
   ],
   "customers": [
    {
     "customer": "Deccan Trucks",
     "product": "Turbo actuator",
     "strategic": true,
     "weeks": 12,
     "revenue_at_risk": 14002560.0,
     "penalty": 280051.2
    },
    {
     "customer": "Bharat Motors",
     "product": "Brake caliper assembly",
     "strategic": true,
     "weeks": 12,
     "revenue_at_risk": 13837824.0,
     "penalty": 276756.48
    },
    {
     "customer": "Bharat Motors",
     "product": "Clutch housing",
     "strategic": true,
     "weeks": 11,
     "revenue_at_risk": 12658602.0,
     "penalty": 253172.04
    },
    {
     "customer": "Volt EV Systems",
     "product": "Brake caliper assembly",
     "strategic": true,
     "weeks": 12,
     "revenue_at_risk": 12370176.0,
     "penalty": 247403.52
    },
    {
     "customer": "Sunrise Tractors",
     "product": "Oil pump assembly",
     "strategic": false,
     "weeks": 12,
     "revenue_at_risk": 11098296.0,
     "penalty": 55491.48
    },
    {
     "customer": "Apex Two-Wheelers",
     "product": "Clutch housing",
     "strategic": false,
     "weeks": 11,
     "revenue_at_risk": 10870398.0,
     "penalty": 54351.99
    },
    {
     "customer": "Bharat Motors",
     "product": "Oil pump assembly",
     "strategic": true,
     "weeks": 12,
     "revenue_at_risk": 10285704.0,
     "penalty": 205714.08
    },
    {
     "customer": "Apex Two-Wheelers",
     "product": "Wiring harness (engine)",
     "strategic": false,
     "weeks": 11,
     "revenue_at_risk": 9982467.0,
     "penalty": 49912.34
    }
   ]
  },
  "port_and_foundry_crisis": {
   "label": "Compound crisis (port + foundry)",
   "totals": {
    "expedite_spend": 6147386.0,
    "baseline_loss": 31053719.76,
    "residual_loss": 13984147.0,
    "loss_avoided": 17069572.76,
    "net_benefit": 10922186.76,
    "accepted_components": [
     "Turbo cartridge core"
    ]
   },
   "components_short": 16,
   "components_total": 24,
   "products": [
    {
     "name": "Brake caliper assembly",
     "weeks_stopped": 12,
     "first_stop": "2026-09-07",
     "margin_at_risk": 3931200.0,
     "penalty": 524160.0,
     "blockers": "C001, C006, C018"
    },
    {
     "name": "Clutch housing",
     "weeks_stopped": 11,
     "first_stop": "2026-09-14",
     "margin_at_risk": 3512300.0,
     "penalty": 307524.03,
     "blockers": "C002, C020"
    },
    {
     "name": "Turbo actuator",
     "weeks_stopped": 12,
     "first_stop": "2026-09-07",
     "margin_at_risk": 3393000.0,
     "penalty": 312998.4,
     "blockers": "C003, C006, C010"
    },
    {
     "name": "Oil pump assembly",
     "weeks_stopped": 12,
     "first_stop": "2026-09-07",
     "margin_at_risk": 3247200.0,
     "penalty": 261205.56,
     "blockers": "C001, C004, C005, C007, C012, C024"
    },
    {
     "name": "Steering knuckle set",
     "weeks_stopped": 12,
     "first_stop": "2026-09-07",
     "margin_at_risk": 3024000.0,
     "penalty": 347099.76,
     "blockers": "C003, C005, C011, C023"
    },
    {
     "name": "Wiring harness (engine)",
     "weeks_stopped": 11,
     "first_stop": "2026-09-14",
     "margin_at_risk": 2885300.0,
     "penalty": 239442.99,
     "blockers": "C004, C018, C024"
    },
    {
     "name": "Fuel rail assembly",
     "weeks_stopped": 11,
     "first_stop": "2026-09-14",
     "margin_at_risk": 2618000.0,
     "penalty": 161453.93,
     "blockers": "C011, C023, C024"
    },
    {
     "name": "Alternator unit",
     "weeks_stopped": 8,
     "first_stop": "2026-09-14",
     "margin_at_risk": 2585600.0,
     "penalty": 252588.88,
     "blockers": "C010"
    },
    {
     "name": "EGR valve module",
     "weeks_stopped": 11,
     "first_stop": "2026-09-14",
     "margin_at_risk": 1630200.0,
     "penalty": 176278.96,
     "blockers": "C011, C018, C022, C023, C024"
    },
    {
     "name": "ECU bracket module",
     "weeks_stopped": 11,
     "first_stop": "2026-09-14",
     "margin_at_risk": 1534500.0,
     "penalty": 109667.25,
     "blockers": "C002, C006, C007, C009, C020"
    }
   ],
   "plan": [
    {
     "component": "Grey-iron caliper casting",
     "option": "alt_supplier",
     "detail": "emergency order 5752 units from Hemavati Foundries (road, 21d lead)",
     "cost": 807580.8,
     "arrival": "2026-09-22"
    },
    {
     "component": "Clutch housing casting",
     "option": "alt_supplier",
     "detail": "emergency order 6002 units from Hemavati Foundries (road, 21d lead)",
     "cost": 1242414.0,
     "arrival": "2026-09-22"
    },
    {
     "component": "Knuckle forging blank",
     "option": "alt_supplier",
     "detail": "emergency order 5522 units from Hemavati Foundries (road, 21d lead)",
     "cost": 934322.4,
     "arrival": "2026-09-22"
    },
    {
     "component": "Pump body casting",
     "option": "alt_supplier",
     "detail": "emergency order 5625 units from Hemavati Foundries (road, 21d lead)",
     "cost": 617625.0,
     "arrival": "2026-09-22"
    },
    {
     "component": "Precision piston (import)",
     "option": "alt_supplier",
     "detail": "emergency order 100 units from Schwarzwald Metall (air, 9d lead)",
     "cost": 33900.0,
     "arrival": "2026-09-10"
    },
    {
     "component": "Turbo cartridge core",
     "option": "accept",
     "detail": "no expedite: absorb lost margin and customer penalties",
     "cost": 3049286.25,
     "arrival": ""
    },
    {
     "component": "Actuator gearset",
     "option": "alt_supplier",
     "detail": "emergency order 1848 units from Schwarzwald Metall (air, 9d lead)",
     "cost": 728112.0,
     "arrival": "2026-09-10"
    },
    {
     "component": "Position sensor IC",
     "option": "alt_supplier",
     "detail": "emergency order 1948 units from Han River Components (sea, 33d lead)",
     "cost": 132853.6,
     "arrival": "2026-10-04"
    },
    {
     "component": "Copper winding set",
     "option": "alt_supplier",
     "detail": "emergency order 3848 units from Han River Components (sea, 33d lead)",
     "cost": 330158.4,
     "arrival": "2026-10-04"
    },
    {
     "component": "Injector seat insert",
     "option": "alt_supplier",
     "detail": "emergency order 2790 units from Schwarzwald Metall (air, 9d lead)",
     "cost": 432450.0,
     "arrival": "2026-09-10"
    },
    {
     "component": "Solenoid coil",
     "option": "alt_supplier",
     "detail": "emergency order 760 units from Han River Components (sea, 33d lead)",
     "cost": 38456.0,
     "arrival": "2026-10-04"
    },
    {
     "component": "Harness connector set",
     "option": "alt_supplier",
     "detail": "emergency order 1172 units from Han River Components (sea, 33d lead)",
     "cost": 30940.8,
     "arrival": "2026-10-04"
    },
    {
     "component": "Aluminium end cover",
     "option": "alt_supplier",
     "detail": "emergency order 2990 units from Hemavati Foundries (road, 21d lead)",
     "cost": 182988.0,
     "arrival": "2026-09-22"
    },
    {
     "component": "Valve stem (import)",
     "option": "alt_supplier",
     "detail": "emergency order 434 units from Schwarzwald Metall (air, 9d lead)",
     "cost": 49693.0,
     "arrival": "2026-09-10"
    },
    {
     "component": "Rotor lamination stack",
     "option": "alt_supplier",
     "detail": "emergency order 2892 units from Han River Components (sea, 33d lead)",
     "cost": 286308.0,
     "arrival": "2026-10-04"
    },
    {
     "component": "Oil seal (single-source)",
     "option": "air_uplift",
     "detail": "fly 24800 units currently stuck in sea freight",
     "cost": 299584.0,
     "arrival": "2026-09-08"
    }
   ],
   "customers": [
    {
     "customer": "Deccan Trucks",
     "product": "Turbo actuator",
     "strategic": true,
     "weeks": 12,
     "revenue_at_risk": 14002560.0,
     "penalty": 280051.2
    },
    {
     "customer": "Bharat Motors",
     "product": "Brake caliper assembly",
     "strategic": true,
     "weeks": 12,
     "revenue_at_risk": 13837824.0,
     "penalty": 276756.48
    },
    {
     "customer": "Bharat Motors",
     "product": "Clutch housing",
     "strategic": true,
     "weeks": 11,
     "revenue_at_risk": 12658602.0,
     "penalty": 253172.04
    },
    {
     "customer": "Volt EV Systems",
     "product": "Brake caliper assembly",
     "strategic": true,
     "weeks": 12,
     "revenue_at_risk": 12370176.0,
     "penalty": 247403.52
    },
    {
     "customer": "Sunrise Tractors",
     "product": "Oil pump assembly",
     "strategic": false,
     "weeks": 12,
     "revenue_at_risk": 11098296.0,
     "penalty": 55491.48
    },
    {
     "customer": "Apex Two-Wheelers",
     "product": "Clutch housing",
     "strategic": false,
     "weeks": 11,
     "revenue_at_risk": 10870398.0,
     "penalty": 54351.99
    },
    {
     "customer": "Bharat Motors",
     "product": "Oil pump assembly",
     "strategic": true,
     "weeks": 12,
     "revenue_at_risk": 10285704.0,
     "penalty": 205714.08
    },
    {
     "customer": "Apex Two-Wheelers",
     "product": "Wiring harness (engine)",
     "strategic": false,
     "weeks": 11,
     "revenue_at_risk": 9982467.0,
     "penalty": 49912.34
    }
   ]
  }
 },
 "order": [
  "baseline",
  "port_congestion",
  "foundry_fire",
  "port_and_foundry_crisis"
 ],
 "notice": "Kaveri Auto Components Ltd is fictional; all data is synthetic and pre-computed. This simulation makes no network calls."
};
