// Pre-computed synthetic results (rules vs ml modes). Generated by a private build tool; no calculation source ships with this page.
const WCT_DATA = {
 "rules": {
  "metrics": {
   "open_ar": 641842535.84,
   "at_risk_ar": 202176720.17000002,
   "days_to_cash": 17.4,
   "auto_match_pct": 99.1,
   "exceptions": 9,
   "exception_value": 15124059.940000001,
   "peak_draw": 149237888.48,
   "interest_cost": 1759383.92
  },
  "predictions": [
   {
    "customer": "Willow Agencies",
    "invoice": "INV01084",
    "open_amount": 14731651.61,
    "due": "2026-08-06",
    "predicted": "2026-09-01",
    "late_risk": 0.46867749419953597,
    "action": "Relationship call: senior-to-senior nudge"
   },
   {
    "customer": "Orchid Engineering",
    "invoice": "INV00101",
    "open_amount": 14666259.78,
    "due": "2026-09-12",
    "predicted": "2026-09-20",
    "late_risk": 0.46867749419953597,
    "action": "Standard dunning cycle"
   },
   {
    "customer": "Trellis Systems",
    "invoice": "INV00505",
    "open_amount": 13499572.8,
    "due": "2026-09-21",
    "predicted": "2026-09-29",
    "late_risk": 0.46867749419953597,
    "action": "Standard dunning cycle"
   },
   {
    "customer": "Tarang Motors",
    "invoice": "INV01191",
    "open_amount": 12919585.28,
    "due": "2026-09-30",
    "predicted": "2026-10-08",
    "late_risk": 0.46867749419953597,
    "action": "Standard dunning cycle"
   },
   {
    "customer": "Mistral Components",
    "invoice": "INV01326",
    "open_amount": 12141291.24,
    "due": "2026-08-07",
    "predicted": "2026-09-01",
    "late_risk": 0.46867749419953597,
    "action": "Relationship call: senior-to-senior nudge"
   },
   {
    "customer": "Willow Agencies",
    "invoice": "INV01076",
    "open_amount": 11532527.18,
    "due": "2026-06-15",
    "predicted": "2026-09-01",
    "late_risk": 0.46867749419953597,
    "action": "Relationship call: senior-to-senior nudge"
   },
   {
    "customer": "Willow Enterprises",
    "invoice": "INV00377",
    "open_amount": 10971063.04,
    "due": "2026-09-07",
    "predicted": "2026-09-15",
    "late_risk": 0.46867749419953597,
    "action": "Standard dunning cycle"
   },
   {
    "customer": "Orchid Engineering",
    "invoice": "INV00087",
    "open_amount": 10585273.38,
    "due": "2026-07-24",
    "predicted": "2026-09-01",
    "late_risk": 0.46867749419953597,
    "action": "Relationship call: senior-to-senior nudge"
   },
   {
    "customer": "Willow Agencies",
    "invoice": "INV01086",
    "open_amount": 9751645.42,
    "due": "2026-09-11",
    "predicted": "2026-09-19",
    "late_risk": 0.46867749419953597,
    "action": "Standard dunning cycle"
   },
   {
    "customer": "Tarang Systems",
    "invoice": "INV01038",
    "open_amount": 9519007.62,
    "due": "2026-08-23",
    "predicted": "2026-09-01",
    "late_risk": 0.46867749419953597,
    "action": "Standard dunning cycle"
   },
   {
    "customer": "Orchid Engineering",
    "invoice": "INV00069",
    "open_amount": 9182474.06,
    "due": "2026-09-28",
    "predicted": "2026-10-06",
    "late_risk": 0.46867749419953597,
    "action": "Standard dunning cycle"
   },
   {
    "customer": "Tarang Motors",
    "invoice": "INV01183",
    "open_amount": 9095121.13,
    "due": "2026-08-17",
    "predicted": "2026-09-01",
    "late_risk": 0.46867749419953597,
    "action": "Relationship call: senior-to-senior nudge"
   }
  ],
  "forecast": [
   {
    "week": "2026-08-31",
    "inflow": 74982289.44000001,
    "outflow": 101506045.42,
    "cum_p10": -7130829.840000004,
    "cum_p50": -26523755.97999999,
    "cum_p90": -59766441.870000005
   },
   {
    "week": "2026-09-07",
    "inflow": 28642006.74,
    "outflow": 71595007.29,
    "cum_p10": -42478676.32000001,
    "cum_p50": -69476756.53,
    "cum_p90": -102923524.76
   },
   {
    "week": "2026-09-14",
    "inflow": 69469617.19999999,
    "outflow": 35110095.28,
    "cum_p10": -17530726.380000003,
    "cum_p50": -35117234.610000014,
    "cum_p90": -120952565.48
   },
   {
    "week": "2026-09-21",
    "inflow": 21798279.32,
    "outflow": 35478547.56,
    "cum_p10": -17626422.21,
    "cum_p50": -48797502.85000002,
    "cum_p90": -120926973.05000001
   },
   {
    "week": "2026-09-28",
    "inflow": 51291002.48,
    "outflow": 68945046.71000001,
    "cum_p10": 10636544.719999991,
    "cum_p50": -66451547.08000003,
    "cum_p90": -123033077.64000002
   },
   {
    "week": "2026-10-05",
    "inflow": 82266788.48000002,
    "outflow": 66237477.64,
    "cum_p10": -29902043.190000013,
    "cum_p50": -50422236.24000001,
    "cum_p90": -154237888.48000002
   },
   {
    "week": "2026-10-12",
    "inflow": 25602039.04,
    "outflow": 48307467.15,
    "cum_p10": -49387067.370000005,
    "cum_p50": -73127664.35000001,
    "cum_p90": -110178977.13000003
   },
   {
    "week": "2026-10-19",
    "inflow": 83823308.18083334,
    "outflow": 41933034.0,
    "cum_p10": -28702383.311625004,
    "cum_p50": -31237390.16916667,
    "cum_p90": -79795738.06179169
   },
   {
    "week": "2026-10-26",
    "inflow": 54816410.71083333,
    "outflow": 51145743.129999995,
    "cum_p10": -592761.4932500124,
    "cum_p50": -27566722.58833333,
    "cum_p90": -58959053.443583354
   },
   {
    "week": "2026-11-02",
    "inflow": 72604084.53083333,
    "outflow": 38917496.650000006,
    "cum_p10": 13724885.865124978,
    "cum_p50": 6119865.292499997,
    "cum_p90": -42715417.36537503
   },
   {
    "week": "2026-11-09",
    "inflow": 50700137.15083333,
    "outflow": 50141208.42,
    "cum_p10": 16818821.453499973,
    "cum_p50": 6678794.023333326,
    "cum_p90": -23741288.267166704
   },
   {
    "week": "2026-11-16",
    "inflow": 50700137.15083333,
    "outflow": 25693976.68,
    "cum_p10": 44359988.78187497,
    "cum_p50": 31684954.494166657,
    "cum_p90": -6340148.368958376
   },
   {
    "week": "2026-11-23",
    "inflow": 50700137.15083333,
    "outflow": 63860761.599999994,
    "cum_p10": 33734371.19024997,
    "cum_p50": 18524330.044999994,
    "cum_p90": -27105793.390750043
   }
  ],
  "treasury": [
   {
    "week": "2026-08-31",
    "action": "draw_wc_line",
    "amount": 54766441.87,
    "line_drawn": 54766441.87,
    "cash_after": 63242685.89
   },
   {
    "week": "2026-09-07",
    "action": "draw_wc_line",
    "amount": 43157082.89,
    "line_drawn": 97923524.76,
    "cash_after": 63446768.23
   },
   {
    "week": "2026-09-14",
    "action": "draw_wc_line",
    "amount": 18029040.72,
    "line_drawn": 115952565.48,
    "cash_after": 115835330.87
   },
   {
    "week": "2026-09-21",
    "action": "repay_wc_line",
    "amount": 25592.43,
    "line_drawn": 115926973.05,
    "cash_after": 102129470.2
   },
   {
    "week": "2026-09-28",
    "action": "draw_wc_line",
    "amount": 2106104.59,
    "line_drawn": 118033077.64,
    "cash_after": 86581530.56
   },
   {
    "week": "2026-10-05",
    "action": "draw_wc_line",
    "amount": 31204810.84,
    "line_drawn": 149237888.48,
    "cash_after": 133815652.24
   },
   {
    "week": "2026-10-12",
    "action": "repay_wc_line",
    "amount": 44058911.35,
    "line_drawn": 105178977.13,
    "cash_after": 67051312.78
   },
   {
    "week": "2026-10-19",
    "action": "repay_wc_line",
    "amount": 30383239.07,
    "line_drawn": 74795738.06,
    "cash_after": 78558347.89
   },
   {
    "week": "2026-10-26",
    "action": "repay_wc_line",
    "amount": 20836684.62,
    "line_drawn": 53959053.44,
    "cash_after": 61392330.86
   },
   {
    "week": "2026-11-02",
    "action": "repay_wc_line",
    "amount": 16243636.08,
    "line_drawn": 37715417.37,
    "cash_after": 78835282.66
   },
   {
    "week": "2026-11-09",
    "action": "repay_wc_line",
    "amount": 18974129.1,
    "line_drawn": 18741288.27,
    "cash_after": 60420082.29
   },
   {
    "week": "2026-11-16",
    "action": "repay_wc_line",
    "amount": 17401139.9,
    "line_drawn": 1340148.37,
    "cash_after": 68025102.86
   },
   {
    "week": "2026-11-23",
    "action": "draw_wc_line",
    "amount": 20765645.02,
    "line_drawn": 22105793.39,
    "cash_after": 75630123.44
   }
  ]
 },
 "ml": {
  "metrics": {
   "open_ar": 641842535.84,
   "at_risk_ar": 399240504.53,
   "days_to_cash": 18.4,
   "auto_match_pct": 99.1,
   "exceptions": 9,
   "exception_value": 15124059.940000001,
   "peak_draw": 125458307.85,
   "interest_cost": 1793667.22
  },
  "predictions": [
   {
    "customer": "Tarang Motors",
    "invoice": "INV01191",
    "open_amount": 12919585.28,
    "due": "2026-09-30",
    "predicted": "2026-10-18",
    "late_risk": 0.924,
    "action": "Call this week: firm promise-to-pay"
   },
   {
    "customer": "Orchid Engineering",
    "invoice": "INV00101",
    "open_amount": 14666259.78,
    "due": "2026-09-12",
    "predicted": "2026-09-21",
    "late_risk": 0.694,
    "action": "Call this week: firm promise-to-pay"
   },
   {
    "customer": "Mistral Components",
    "invoice": "INV01326",
    "open_amount": 12141291.24,
    "due": "2026-08-07",
    "predicted": "2026-09-01",
    "late_risk": 0.826,
    "action": "Call this week: firm promise-to-pay"
   },
   {
    "customer": "Willow Enterprises",
    "invoice": "INV00377",
    "open_amount": 10971063.04,
    "due": "2026-09-07",
    "predicted": "2026-09-20",
    "late_risk": 0.894,
    "action": "Call this week: firm promise-to-pay"
   },
   {
    "customer": "Willow Agencies",
    "invoice": "INV01086",
    "open_amount": 9751645.42,
    "due": "2026-09-11",
    "predicted": "2026-09-30",
    "late_risk": 0.924,
    "action": "Call this week: firm promise-to-pay"
   },
   {
    "customer": "Tarang Motors",
    "invoice": "INV01183",
    "open_amount": 9095121.13,
    "due": "2026-08-17",
    "predicted": "2026-09-06",
    "late_risk": 0.962,
    "action": "Call this week: firm promise-to-pay"
   },
   {
    "customer": "Mistral Components",
    "invoice": "INV01351",
    "open_amount": 9088223.85,
    "due": "2026-08-06",
    "predicted": "2026-09-01",
    "late_risk": 0.935,
    "action": "Call this week: firm promise-to-pay"
   },
   {
    "customer": "Willow Agencies",
    "invoice": "INV01076",
    "open_amount": 11532527.18,
    "due": "2026-06-15",
    "predicted": "2026-09-01",
    "late_risk": 0.721,
    "action": "Call this week: firm promise-to-pay"
   },
   {
    "customer": "Willow Agencies",
    "invoice": "INV01084",
    "open_amount": 14731651.61,
    "due": "2026-08-06",
    "predicted": "2026-09-01",
    "late_risk": 0.547,
    "action": "Relationship call: senior-to-senior nudge"
   },
   {
    "customer": "Orchid Engineering",
    "invoice": "INV00069",
    "open_amount": 9182474.06,
    "due": "2026-09-28",
    "predicted": "2026-10-09",
    "late_risk": 0.871,
    "action": "Call this week: firm promise-to-pay"
   },
   {
    "customer": "Orchid Engineering",
    "invoice": "INV00087",
    "open_amount": 10585273.38,
    "due": "2026-07-24",
    "predicted": "2026-09-01",
    "late_risk": 0.689,
    "action": "Call this week: firm promise-to-pay"
   },
   {
    "customer": "Orchid Engineering",
    "invoice": "INV00117",
    "open_amount": 8092081.94,
    "due": "2026-10-06",
    "predicted": "2026-10-18",
    "late_risk": 0.842,
    "action": "Call this week: firm promise-to-pay"
   }
  ],
  "forecast": [
   {
    "week": "2026-08-31",
    "inflow": 66132354.57999999,
    "outflow": 101506045.42,
    "cum_p10": 1058034.019999981,
    "cum_p50": -35373690.84000001,
    "cum_p90": -67012657.6
   },
   {
    "week": "2026-09-07",
    "inflow": 43610606.58,
    "outflow": 71595007.29,
    "cum_p10": -24774339.19000002,
    "cum_p50": -63358091.55000002,
    "cum_p90": -116838212.42000002
   },
   {
    "week": "2026-09-14",
    "inflow": 43396819.59,
    "outflow": 35110095.28,
    "cum_p10": 12296715.109999992,
    "cum_p50": -55071367.24000002,
    "cum_p90": -128871655.08000001
   },
   {
    "week": "2026-09-21",
    "inflow": 61587549.01000001,
    "outflow": 35478547.56,
    "cum_p10": 21865667.299999997,
    "cum_p50": -28962365.790000007,
    "cum_p90": -82445309.88000001
   },
   {
    "week": "2026-09-28",
    "inflow": 44950119.559999995,
    "outflow": 68945046.71000001,
    "cum_p10": -2486331.2200000137,
    "cum_p50": -52957292.94000002,
    "cum_p90": -94948445.27000001
   },
   {
    "week": "2026-10-05",
    "inflow": 48476482.42000002,
    "outflow": 66237477.64,
    "cum_p10": -26485284.530000016,
    "cum_p50": -70718288.16,
    "cum_p90": -119870765.45000002
   },
   {
    "week": "2026-10-12",
    "inflow": 33246218.34,
    "outflow": 48307467.15,
    "cum_p10": -56287969.27000001,
    "cum_p50": -85779536.97,
    "cum_p90": -130458307.85000002
   },
   {
    "week": "2026-10-19",
    "inflow": 74650796.39083333,
    "outflow": 41933034.0,
    "cum_p10": -25493984.20162502,
    "cum_p50": -53061774.579166666,
    "cum_p90": -100742161.01179169
   },
   {
    "week": "2026-10-26",
    "inflow": 72294087.63083333,
    "outflow": 51145743.129999995,
    "cum_p10": -8414096.753250018,
    "cum_p50": -31913430.078333333,
    "cum_p90": -84840932.42358336
   },
   {
    "week": "2026-11-02",
    "inflow": 67371088.91083333,
    "outflow": 38917496.650000006,
    "cum_p10": 13724885.86512497,
    "cum_p50": -3459837.81750001,
    "cum_p90": -43306522.16537504
   },
   {
    "week": "2026-11-09",
    "inflow": 56201454.66083333,
    "outflow": 50141208.42,
    "cum_p10": 16818821.453499965,
    "cum_p50": 2600408.423333317,
    "cum_p90": -37093831.47716671
   },
   {
    "week": "2026-11-16",
    "inflow": 52030212.45083333,
    "outflow": 25693976.68,
    "cum_p10": 44359988.78187496,
    "cum_p50": 28936644.194166645,
    "cum_p90": -15959442.428958386
   },
   {
    "week": "2026-11-23",
    "inflow": 53448447.45083333,
    "outflow": 63860761.599999994,
    "cum_p10": 33734371.190249965,
    "cum_p50": 18524330.04499998,
    "cum_p90": -27105793.39075005
   }
  ],
  "treasury": [
   {
    "week": "2026-08-31",
    "action": "draw_wc_line",
    "amount": 62012657.6,
    "line_drawn": 62012657.6,
    "cash_after": 61638966.76
   },
   {
    "week": "2026-09-07",
    "action": "draw_wc_line",
    "amount": 49825554.82,
    "line_drawn": 111838212.42,
    "cash_after": 83480120.87
   },
   {
    "week": "2026-09-14",
    "action": "draw_wc_line",
    "amount": 12033442.66,
    "line_drawn": 123871655.08,
    "cash_after": 103800287.84
   },
   {
    "week": "2026-09-21",
    "action": "repay_wc_line",
    "amount": 46426345.2,
    "line_drawn": 77445309.88,
    "cash_after": 83482944.09
   },
   {
    "week": "2026-09-28",
    "action": "draw_wc_line",
    "amount": 12503135.39,
    "line_drawn": 89948445.27,
    "cash_after": 71991152.33
   },
   {
    "week": "2026-10-05",
    "action": "draw_wc_line",
    "amount": 24922320.18,
    "line_drawn": 114870765.45,
    "cash_after": 79152477.29
   },
   {
    "week": "2026-10-12",
    "action": "draw_wc_line",
    "amount": 10587542.4,
    "line_drawn": 125458307.85,
    "cash_after": 74678770.88
   },
   {
    "week": "2026-10-19",
    "action": "repay_wc_line",
    "amount": 29716146.84,
    "line_drawn": 95742161.01,
    "cash_after": 77680386.43
   },
   {
    "week": "2026-10-26",
    "action": "repay_wc_line",
    "amount": 15901228.59,
    "line_drawn": 79840932.42,
    "cash_after": 82927502.35
   },
   {
    "week": "2026-11-02",
    "action": "repay_wc_line",
    "amount": 41534410.26,
    "line_drawn": 38306522.17,
    "cash_after": 69846684.35
   },
   {
    "week": "2026-11-09",
    "action": "repay_wc_line",
    "amount": 6212690.69,
    "line_drawn": 32093831.48,
    "cash_after": 69694239.9
   },
   {
    "week": "2026-11-16",
    "action": "repay_wc_line",
    "amount": 21134389.05,
    "line_drawn": 10959442.43,
    "cash_after": 74896086.62
   },
   {
    "week": "2026-11-23",
    "action": "draw_wc_line",
    "amount": 11146350.96,
    "line_drawn": 22105793.39,
    "cash_after": 75630123.44
   }
  ]
 },
 "exceptions": [
  {
   "bank_txn_id": "BT0039",
   "kind": "PARTIAL_PAYMENT",
   "amount": 521299.08,
   "detail": "INV00685: received 521,299 of 616,990 open \u2014 chase balance or check for dispute/credit note"
  },
  {
   "bank_txn_id": "BT0063",
   "kind": "UNKNOWN_PAYER",
   "amount": 94873.02,
   "detail": "payer 'BANK', reference 'INTEREST CREDIT SWEEP'"
  },
  {
   "bank_txn_id": "BT0009",
   "kind": "PARTIAL_PAYMENT",
   "amount": 1254892.26,
   "detail": "INV01138: received 1,254,892 of 2,213,807 open \u2014 chase balance or check for dispute/credit note"
  },
  {
   "bank_txn_id": "BT0011",
   "kind": "PARTIAL_PAYMENT",
   "amount": 3435841.43,
   "detail": "INV00346: received 3,435,841 of 7,153,632 open \u2014 chase balance or check for dispute/credit note"
  },
  {
   "bank_txn_id": "BT0010",
   "kind": "PARTIAL_PAYMENT",
   "amount": 1229709.73,
   "detail": "INV01160: received 1,229,710 of 3,014,031 open \u2014 chase balance or check for dispute/credit note"
  },
  {
   "bank_txn_id": "BT0034",
   "kind": "PARTIAL_PAYMENT",
   "amount": 6420303.9,
   "detail": "INV01351: received 6,420,304 of 9,088,224 open \u2014 chase balance or check for dispute/credit note"
  },
  {
   "bank_txn_id": "BT0065",
   "kind": "UNKNOWN_PAYER",
   "amount": 1169994.11,
   "detail": "payer 'BANK', reference 'FX CONVERSION EXPORT ADV'"
  },
  {
   "bank_txn_id": "BT0045",
   "kind": "UNMATCHED_RECEIPT",
   "amount": 704244.27,
   "detail": "payer 'Iris Industries', reference 'PAYMENT RECEIVED'"
  },
  {
   "bank_txn_id": "BT0064",
   "kind": "UNKNOWN_PAYER",
   "amount": 292902.14,
   "detail": "payer 'BANK', reference 'GST REFUND'"
  }
 ],
 "notice": "Kaveri Auto Components Ltd is fictional; all data is synthetic and pre-computed. This simulation makes no network calls."
};
