// Pre-computed synthetic forensics + a recorded swarm trace. Generated by a private build tool; no calculation source ships with this page.
const MECF_DATA = {
 "month": "2026-08",
 "totals": {
  "total_overspend": 8477499.99,
  "flagged_items": 3,
  "approved_variance": 6100000.0,
  "avoidable_leak": 1834009.32,
  "process_gap_monthly": 162000.0,
  "recoverable": 1042324.47,
  "unexplained": 0.0
 },
 "variance": [
  {
   "cost_center": "Logistics",
   "account": "Freight",
   "budget": 11000000.0,
   "actual": 17105000.0,
   "variance": 6105000.0,
   "variance_pct": 55.5,
   "flagged": true
  },
  {
   "cost_center": "IT & Digital",
   "account": "Cloud Compute",
   "budget": 7500000.0,
   "actual": 9322500.0,
   "variance": 1822500.0,
   "variance_pct": 24.3,
   "flagged": true
  },
  {
   "cost_center": "IT & Digital",
   "account": "SaaS Subscriptions",
   "budget": 2200000.0,
   "actual": 2749999.9899999998,
   "variance": 549999.9899999998,
   "variance_pct": 25.0,
   "flagged": true
  },
  {
   "cost_center": "Manufacturing",
   "account": "Power & Fuel",
   "budget": 14500000.0,
   "actual": 15046299.71,
   "variance": 546299.7100000009,
   "variance_pct": 3.8,
   "flagged": false
  },
  {
   "cost_center": "Manufacturing",
   "account": "Maintenance & Spares",
   "budget": 8500000.0,
   "actual": 8658620.84,
   "variance": 158620.83999999985,
   "variance_pct": 1.9,
   "flagged": false
  },
  {
   "cost_center": "HR & Admin",
   "account": "Contract Staffing",
   "budget": 6500000.0,
   "actual": 6641246.49,
   "variance": 141246.49000000022,
   "variance_pct": 2.2,
   "flagged": false
  },
  {
   "cost_center": "Logistics",
   "account": "Warehousing",
   "budget": 4200000.0,
   "actual": 4331629.39,
   "variance": 131629.38999999966,
   "variance_pct": 3.1,
   "flagged": false
  },
  {
   "cost_center": "Sales & Marketing",
   "account": "Travel",
   "budget": 2800000.0,
   "actual": 2888168.92,
   "variance": 88168.91999999993,
   "variance_pct": 3.1,
   "flagged": false
  },
  {
   "cost_center": "IT & Digital",
   "account": "Telecom & Network",
   "budget": 1100000.0,
   "actual": 1061563.17,
   "variance": -38436.830000000075,
   "variance_pct": -3.5,
   "flagged": false
  },
  {
   "cost_center": "Quality",
   "account": "Testing & Calibration",
   "budget": 3000000.0,
   "actual": 2911560.73,
   "variance": -88439.27000000002,
   "variance_pct": -2.9,
   "flagged": false
  },
  {
   "cost_center": "HR & Admin",
   "account": "Facilities",
   "budget": 3400000.0,
   "actual": 3300126.1,
   "variance": -99873.8999999999,
   "variance_pct": -2.9,
   "flagged": false
  },
  {
   "cost_center": "Manufacturing",
   "account": "Raw Material Consumables",
   "budget": 26000000.0,
   "actual": 25802055.73,
   "variance": -197944.26999999955,
   "variance_pct": -0.8,
   "flagged": false
  },
  {
   "cost_center": "Sales & Marketing",
   "account": "Dealer Incentives",
   "budget": 9500000.0,
   "actual": 9146652.53,
   "variance": -353347.47000000067,
   "variance_pct": -3.7,
   "flagged": false
  }
 ],
 "findings": [
  {
   "cost_center": "Logistics",
   "account": "Freight",
   "variance": 6105000.0,
   "variance_pct": 55.5,
   "root_cause": "Emergency air freight + alternate supplier premium (supply-chain war room: port congestion + foundry fire)",
   "classification": "APPROVED",
   "amount": 6100000.0,
   "recoverable": 0.0,
   "evidence": "approvals_register.csv A-2026-081 approved by COO + CFO on 2026-08-30",
   "corrective_action": "None \u2014 governed spend; confirm the ledger line maps to the approval"
  },
  {
   "cost_center": "IT & Digital",
   "account": "Cloud Compute",
   "variance": 1822500.0,
   "variance_pct": 24.3,
   "root_cause": "Unreserved GPU compute 2026-08-12..2026-08-16 on gpu-train-cluster-07 \u2014 attributed to PR-412 (Data Science): Demand-forecast model retraining pipeline v2 (distributed GPU run; no auto-shutdown policy)",
   "classification": "AVOIDABLE_LEAK",
   "amount": 1834009.32,
   "recoverable": 880324.47,
   "evidence": "cloud_billing.csv on_demand rows; deploy_log.csv cluster=ml-staging; contract NC-EDP-2025 (48% savings plan not applied)",
   "corrective_action": "Tag-based auto-shutdown on ML clusters; route training to committed capacity; request a one-time courtesy credit from the vendor"
  },
  {
   "cost_center": "IT & Digital",
   "account": "SaaS Subscriptions",
   "variance": 549999.99,
   "variance_pct": 25.0,
   "root_cause": "Duplicate Business Intelligence stack: Lumina BI Suite vs InsightGrid Dashboards",
   "classification": "PROCESS_GAP",
   "amount": 117000.0,
   "recoverable": 117000.0,
   "evidence": "saas_subscriptions.csv \u2014 InsightGrid Dashboards avg last login 71d",
   "corrective_action": "Consolidate on the used tool; cancel InsightGrid Dashboards at renewal"
  },
  {
   "cost_center": "IT & Digital",
   "account": "SaaS Subscriptions",
   "variance": 549999.99,
   "variance_pct": 25.0,
   "root_cause": "PulseBoard OKR Tracker: 30 seats, no login in 95 days",
   "classification": "PROCESS_GAP",
   "amount": 45000.0,
   "recoverable": 45000.0,
   "evidence": "saas_subscriptions.csv usage telemetry",
   "corrective_action": "Cancel or downsize; owner HR & Admin to confirm by Friday"
  }
 ],
 "cloud_daily": [
  {
   "usage_date": "2026-08-01",
   "on_demand": 0.0,
   "savings_plan": 258107.65
  },
  {
   "usage_date": "2026-08-02",
   "on_demand": 0.0,
   "savings_plan": 235685.61
  },
  {
   "usage_date": "2026-08-03",
   "on_demand": 0.0,
   "savings_plan": 245518.68
  },
  {
   "usage_date": "2026-08-04",
   "on_demand": 0.0,
   "savings_plan": 254984.96
  },
  {
   "usage_date": "2026-08-05",
   "on_demand": 0.0,
   "savings_plan": 235130.86
  },
  {
   "usage_date": "2026-08-06",
   "on_demand": 0.0,
   "savings_plan": 247531.72
  },
  {
   "usage_date": "2026-08-07",
   "on_demand": 0.0,
   "savings_plan": 247385.47
  },
  {
   "usage_date": "2026-08-08",
   "on_demand": 0.0,
   "savings_plan": 238293.63
  },
  {
   "usage_date": "2026-08-09",
   "on_demand": 0.0,
   "savings_plan": 229494.34
  },
  {
   "usage_date": "2026-08-10",
   "on_demand": 0.0,
   "savings_plan": 249582.03
  },
  {
   "usage_date": "2026-08-11",
   "on_demand": 0.0,
   "savings_plan": 250131.55
  },
  {
   "usage_date": "2026-08-12",
   "on_demand": 368397.1,
   "savings_plan": 254733.45
  },
  {
   "usage_date": "2026-08-13",
   "on_demand": 355489.49,
   "savings_plan": 229625.13
  },
  {
   "usage_date": "2026-08-14",
   "on_demand": 373203.55,
   "savings_plan": 254128.42
  },
  {
   "usage_date": "2026-08-15",
   "on_demand": 368515.07,
   "savings_plan": 228626.85
  },
  {
   "usage_date": "2026-08-16",
   "on_demand": 368404.11,
   "savings_plan": 255028.54
  },
  {
   "usage_date": "2026-08-17",
   "on_demand": 0.0,
   "savings_plan": 245547.46
  },
  {
   "usage_date": "2026-08-18",
   "on_demand": 0.0,
   "savings_plan": 253651.65
  },
  {
   "usage_date": "2026-08-19",
   "on_demand": 0.0,
   "savings_plan": 233110.7
  },
  {
   "usage_date": "2026-08-20",
   "on_demand": 0.0,
   "savings_plan": 249758.41
  },
  {
   "usage_date": "2026-08-21",
   "on_demand": 0.0,
   "savings_plan": 238828.22
  },
  {
   "usage_date": "2026-08-22",
   "on_demand": 0.0,
   "savings_plan": 257688.65
  },
  {
   "usage_date": "2026-08-23",
   "on_demand": 0.0,
   "savings_plan": 232087.42
  },
  {
   "usage_date": "2026-08-24",
   "on_demand": 0.0,
   "savings_plan": 234302.83
  },
  {
   "usage_date": "2026-08-25",
   "on_demand": 0.0,
   "savings_plan": 235954.42
  },
  {
   "usage_date": "2026-08-26",
   "on_demand": 0.0,
   "savings_plan": 237785.33
  },
  {
   "usage_date": "2026-08-27",
   "on_demand": 0.0,
   "savings_plan": 250357.79
  },
  {
   "usage_date": "2026-08-28",
   "on_demand": 0.0,
   "savings_plan": 232181.68
  },
  {
   "usage_date": "2026-08-29",
   "on_demand": 0.0,
   "savings_plan": 225975.47
  },
  {
   "usage_date": "2026-08-30",
   "on_demand": 0.0,
   "savings_plan": 247494.3
  },
  {
   "usage_date": "2026-08-31",
   "on_demand": 0.0,
   "savings_plan": 232956.79
  }
 ],
 "deploys": [
  {
   "deploy_date": "2026-08-12",
   "team": "Data Science",
   "change_id": "PR-412",
   "description": "Demand-forecast model retraining pipeline v2 (distributed GPU run; no auto-shutdown policy)",
   "cluster": "ml-staging"
  },
  {
   "deploy_date": "2026-08-05",
   "team": "Platform",
   "change_id": "PR-398",
   "description": "Dealer portal patch rollout",
   "cluster": "prod-apps"
  },
  {
   "deploy_date": "2026-08-21",
   "team": "Platform",
   "change_id": "PR-431",
   "description": "Log retention cleanup",
   "cluster": "prod-apps"
  }
 ],
 "swarm_events": [
  {
   "ts": 1790082521.557,
   "type": "run_start",
   "request": "/investigate-variance: the CFO signs the close on Friday. Attribute every flagged variance \u2014 what is approved, what leaked, what is structural \u2014 and list exactly what to sign this week.",
   "provider": "openai",
   "model": "gpt-5.6-luna",
   "orchestrator": "close-controller",
   "specialists": [
    "ledger_agent",
    "telemetry_agent",
    "contract_audit_agent",
    "spend_hygiene_agent"
   ]
  },
  {
   "ts": 1790082521.557,
   "type": "agent_start",
   "agent": "close-controller",
   "task": "/investigate-variance: the CFO signs the close on Friday. Attribute every flagged variance \u2014 what is approved, what leaked, what is structural \u2014 and list exactl"
  },
  {
   "ts": 1790082527.665,
   "type": "tool_call",
   "agent": "close-controller",
   "tool": "ledger_agent",
   "args": "{\"task\": \"Act as variance sentry. Identify every flagged variance, its exact INR lakh amount, grain, period, and whether"
  },
  {
   "ts": 1790082527.666,
   "type": "agent_start",
   "agent": "ledger_agent",
   "task": "Act as variance sentry. Identify every flagged variance, its exact INR lakh amount, grain, period, and whether it is approved, avoidable leakage, or structural/"
  },
  {
   "ts": 1790082529.961,
   "type": "tool_call",
   "agent": "ledger_agent",
   "tool": "get_variance_table",
   "args": "{}"
  },
  {
   "ts": 1790082530.858,
   "type": "tool_call",
   "agent": "ledger_agent",
   "tool": "get_gl_actuals",
   "args": "{}"
  },
  {
   "ts": 1790082543.291,
   "type": "agent_done",
   "agent": "ledger_agent",
   "preview": "## Variance sentry \u2014 Kaveri month-end close\n\n**Period:** August 2026  \n**Currency:** INR lakh  \n**Reconciliation basis:** variance table and GL vendor detail on"
  },
  {
   "ts": 1790082543.292,
   "type": "tool_call",
   "agent": "close-controller",
   "tool": "telemetry_agent",
   "args": "{\"task\": \"Act as billing/engineering detective. Join billing telemetry to engineering changes and attribute each flagged"
  },
  {
   "ts": 1790082543.292,
   "type": "agent_start",
   "agent": "telemetry_agent",
   "task": "Act as billing/engineering detective. Join billing telemetry to engineering changes and attribute each flagged variance to approved scope/change, leakage, or st"
  },
  {
   "ts": 1790082545.181,
   "type": "tool_call",
   "agent": "telemetry_agent",
   "tool": "get_cloud_billing",
   "args": "{}"
  },
  {
   "ts": 1790082545.188,
   "type": "tool_call",
   "agent": "telemetry_agent",
   "tool": "get_deploy_log",
   "args": "{}"
  },
  {
   "ts": 1790082556.189,
   "type": "agent_done",
   "agent": "telemetry_agent",
   "preview": "## Billing\u2013engineering variance attribution\n\n### Flagged variance: GPU on-demand spend in `ml-staging`\n\n| Window | Billing evidence | Engineering match | Attrib"
  },
  {
   "ts": 1790082556.189,
   "type": "tool_call",
   "agent": "close-controller",
   "tool": "contract_audit_agent",
   "args": "{\"task\": \"Act as commercial shield. Test negotiated contract terms against billed amounts for every flagged variance. Qu"
  },
  {
   "ts": 1790082556.19,
   "type": "agent_start",
   "agent": "contract_audit_agent",
   "task": "Act as commercial shield. Test negotiated contract terms against billed amounts for every flagged variance. Quantify exact INR lakh over/undercharges, classify "
  },
  {
   "ts": 1790082558.269,
   "type": "tool_call",
   "agent": "contract_audit_agent",
   "tool": "get_vendor_contracts",
   "args": "{}"
  },
  {
   "ts": 1790082558.275,
   "type": "tool_call",
   "agent": "contract_audit_agent",
   "tool": "get_cloud_billing",
   "args": "{}"
  },
  {
   "ts": 1790082558.281,
   "type": "tool_call",
   "agent": "contract_audit_agent",
   "tool": "get_findings",
   "args": "{}"
  },
  {
   "ts": 1790082571.242,
   "type": "agent_done",
   "agent": "contract_audit_agent",
   "preview": "## Commercial shield review\n\n### Executive conclusion\n- **Total flagged variance:** **\u20b91,402.25 lakh**\n- **Approved/governed spend:** **\u20b9610.00 lakh** \u2014 no reco"
  },
  {
   "ts": 1790082571.242,
   "type": "tool_call",
   "agent": "close-controller",
   "tool": "spend_hygiene_agent",
   "args": "{\"task\": \"Act as governance reviewer. Examine approval traceability, SaaS waste, recurring spend, and process gaps behin"
  },
  {
   "ts": 1790082571.243,
   "type": "agent_start",
   "agent": "spend_hygiene_agent",
   "task": "Act as governance reviewer. Examine approval traceability, SaaS waste, recurring spend, and process gaps behind every flagged variance. Quantify exact INR lakh "
  },
  {
   "ts": 1790082573.317,
   "type": "tool_call",
   "agent": "spend_hygiene_agent",
   "tool": "get_approvals_register",
   "args": "{}"
  },
  {
   "ts": 1790082573.322,
   "type": "tool_call",
   "agent": "spend_hygiene_agent",
   "tool": "get_saas_subscriptions",
   "args": "{}"
  },
  {
   "ts": 1790082573.326,
   "type": "tool_call",
   "agent": "spend_hygiene_agent",
   "tool": "get_variance_table",
   "args": "{}"
  },
  {
   "ts": 1790082602.713,
   "type": "agent_done",
   "agent": "spend_hygiene_agent",
   "preview": "## Governance review\n\n### Executive conclusion\nTwo of the three flagged variances have clear signed approval support:\n\n- **Logistics / Freight:** \u20b961.00 lakh ap"
  },
  {
   "ts": 1790082602.726,
   "type": "tool_call",
   "agent": "close-controller",
   "tool": "get_forensic_memo",
   "args": "{}"
  },
  {
   "ts": 1790082616.433,
   "type": "agent_done",
   "agent": "close-controller",
   "preview": "# CFO variance-forensics recommendation \u2014 August 2026 close\n\n**Recommendation:** sign the close with the three flagged variances recorded as exceptions, but do "
  },
  {
   "ts": 1790082616.434,
   "type": "run_done"
  }
 ],
 "notice": "Kaveri Auto Components Ltd is fictional; all data is synthetic and pre-computed, and the swarm replay is the actual recorded trace of one live run. This simulation makes no network calls."
};
