// Pre-computed synthetic diligence results. Generated by a private build tool; no calculation source ships with this page.
const DDR_DATA = {
 "summary": {
  "asking_price": 850000000.0,
  "as_presented": 864000000.0,
  "adjusted_base": 627807282.23,
  "bear": 239583880.86,
  "reported_ebitda": 144000000.0,
  "adjusted_ebitda": 127516903.49,
  "revenue": 960000000.0,
  "multiple": 6.0,
  "gap_vs_asking": -222192717.77,
  "walk_away_price": 596416918.12,
  "top_customer_share": 0.4384
 },
 "findings": [
  {
   "finding_id": "F1",
   "category": "revenue_quality",
   "severity": "HIGH",
   "title": "Customer concentration: Ashva Motors is 44% of trailing-12M revenue",
   "evidence": "monthly_revenue.csv aggregated by customer",
   "valuation_impact": 0.0,
   "impact_note": "priced via the customer-loss bear case"
  },
  {
   "finding_id": "F2",
   "category": "revenue_quality",
   "severity": "HIGH",
   "title": "Ashva Motors volumes -14% over 24 months while revenue +0% \u2014 price increases are masking a shrinking account",
   "evidence": "monthly_revenue.csv volume vs revenue trend; contract price-cap clause 7.3 limits further increases",
   "valuation_impact": 0.0,
   "impact_note": "raises probability of the bear case"
  },
  {
   "finding_id": "F3",
   "category": "earnings_quality",
   "severity": "HIGH",
   "title": "Related-party sales: Varaha Autocomp Trading (9% of revenue) at non-arm's-length terms",
   "evidence": "related_parties.csv; contract K-002 annexure pricing last benchmarked 2019; 15-day payment terms vs 45-60 for others",
   "valuation_impact": -16483096.51,
   "impact_note": "EBITDA adjustment: excess margin treated as non-recurring"
  },
  {
   "finding_id": "F4",
   "category": "legal",
   "severity": "CRITICAL",
   "title": "Change-of-control consent required on the Ashva Motors contract (44% of revenue)",
   "evidence": "contracts.csv K-001; extract ashva_msa_extract.md clause 14.2 (termination on 60 days' notice)",
   "valuation_impact": 0.0,
   "impact_note": "must be a condition precedent to closing"
  },
  {
   "finding_id": "F5",
   "category": "operations",
   "severity": "MEDIUM",
   "title": "Machine park averages 13 years; 15 of 28 machines past service life",
   "evidence": "asset_register.csv ages vs book value; reported capex ~1.2% of revenue is below maintenance level",
   "valuation_impact": -90985919.53,
   "impact_note": "one-time capex catch-up deducted from price"
  },
  {
   "finding_id": "F6",
   "category": "operations",
   "severity": "HIGH",
   "title": "Key-person risk: 2 employees hold undocumented CNC process knowledge; 1 already resigned",
   "evidence": "hr_census.csv critical_knowledge_holder flags and status",
   "valuation_impact": 0.0,
   "impact_note": "retention agreements + documentation plan as closing condition"
  },
  {
   "finding_id": "F7",
   "category": "legal",
   "severity": "MEDIUM",
   "title": "Un-provisioned litigation exposure of \u20b94.5 cr (GST demand + labour matter)",
   "evidence": "litigation_register.csv amounts vs provisions",
   "valuation_impact": -44500000.0,
   "impact_note": "price deduction or escrow/indemnity"
  },
  {
   "finding_id": "F8",
   "category": "working_capital",
   "severity": "MEDIUM",
   "title": "Collectability: 50% of Metro Bus Works receivables are 90+ days old",
   "evidence": "receivables_aging.csv",
   "valuation_impact": -1808219.18,
   "impact_note": "50% provision on the 90+ bucket as a price adjustment"
  }
 ],
 "bridge": [
  {
   "step": "As presented (reported EBITDA x multiple)",
   "value": 864000000.0
  },
  {
   "step": "Related-party margin adjustment (x multiple)",
   "value": -98898579.06
  },
  {
   "step": "Capex catch-up (one-time)",
   "value": -90985919.53
  },
  {
   "step": "Litigation exposure",
   "value": -44500000.0
  },
  {
   "step": "Receivables provision",
   "value": -1808219.18
  },
  {
   "step": "Adjusted base value",
   "value": 627807282.23
  }
 ],
 "scenarios": [
  {
   "scenario": "As presented",
   "ebitda": 144000000.0,
   "value": 864000000.0,
   "note": "Seller's story: reported EBITDA, no adjustments"
  },
  {
   "scenario": "Adjusted base",
   "ebitda": 127516903.49,
   "value": 627807282.23,
   "note": "Quality-of-earnings + one-time deductions"
  },
  {
   "scenario": "Bear (top customer exits)",
   "ebitda": 62813003.26,
   "value": 239583880.86,
   "note": "Change-of-control consent refused or volumes keep sliding"
  }
 ],
 "extracts": {
  "ashva_msa_extract.md": "# Master Supply Agreement \u2014 Ashva Motors / Varaha Precision Works (extract)\n\n**Clause 14.2 \u2014 Change of Control.** In the event of any change in the\nownership or control of the Supplier, including transfer of more than 26%\nof equity or of management control, the Supplier shall obtain the prior\nwritten consent of the Buyer. Absent such consent, the Buyer may\nterminate this Agreement with sixty (60) days' notice without penalty.\n\n**Clause 9.1 \u2014 Exclusivity.** Supplier shall not supply Listed Parts to\nany competitor of the Buyer in the two-wheeler OEM segment during the\nterm.\n\n**Clause 7.3 \u2014 Price Variation.** Price revisions capped at PPI + 2%\nannually; revisions above the cap require joint cost audit.\n",
  "deccan_supply_extract.md": "# Supply Agreement \u2014 Deccan Trucks (extract)\n\n**Clause 11 \u2014 Assignment.** Either party may assign this Agreement to an\naffiliate or successor in interest upon written notice. No consent\nrequirement applies.\n\n**Clause 6 \u2014 Renewal.** Auto-renews annually unless 90 days' notice.\n",
  "related_party_po_extract.md": "# Standing Purchase Terms \u2014 Varaha Autocomp Trading (extract)\n\nOpen-ended standing order, prices per the annexure signed by the\nManaging Director. Annexure prices were last benchmarked in 2019.\nPayment terms: 15 days (all other customers: 45-60 days).\n"
 },
 "notice": "Project Anvil, Kaveri Auto Components and Varaha Precision Works are fictional; all data synthetic and pre-computed. This simulation makes no network calls."
};
