# KateelLearningDemos Attribution Marker - vinallcontact@gmail.com
# Attribution: vinallcontact@gmail.com
"""
AI Product Roadmap Planner
Strategic planning tool for AI product lifecycle
"""

import json
from datetime import datetime, timedelta
from dataclasses import dataclass, asdict
from typing import List, Optional

@dataclass
class RoadmapPhase:
    name: str
    start_month: int
    duration_months: int
    description: str
    key_deliverables: List[str]
    success_criteria: List[str]

@dataclass
class AIRoadmap:
    product_name: str
    vision: str
    phases: List[RoadmapPhase]
    
    def to_dict(self):
        return {
            "product_name": self.product_name,
            "vision": self.vision,
            "phases": [asdict(p) for p in self.phases]
        }

# Pre-defined AI product phases
PHASE_TEMPLATES = {
    "discovery": RoadmapPhase(
        name="Discovery & Planning",
        duration_months=2,
        description="Define problem, gather requirements, assess feasibility",
        key_deliverables=["Problem statement", "Data assessment", "Feasibility study", "PRD"],
        success_criteria=["Stakeholder alignment", "Data availability confirmed", "ROI estimate"]
    ),
    "data": RoadmapPhase(
        name="Data & Infrastructure",
        duration_months=3,
        description="Build data pipeline, collect/label data, set up infrastructure",
        key_deliverables=["Data pipeline", "Labeled dataset", "Infrastructure setup", "Model registry"],
        success_criteria=["Data quality > 95%", "Pipeline automated", "Environment ready"]
    ),
    "development": RoadmapPhase(
        name="Model Development",
        duration_months=4,
        description="Build, train, and validate models with offline evaluation",
        key_deliverables=["Trained models", "Validation results", "Bias/fairness analysis"],
        success_criteria=["Target metrics achieved", "Fairness validated", "Model documented"]
    ),
    "deployment": RoadmapPhase(
        name="Deployment & Testing",
        duration_months=2,
        description="Deploy to staging, run A/B tests, prepare for production",
        key_deliverables=["Staging deployment", "A/B test results", "Monitoring setup"],
        success_criteria=["Performance validated", "Monitoring active", "Rollback plan ready"]
    ),
    "production": RoadmapPhase(
        name="Production Rollout",
        duration_months=2,
        description="Gradual rollout with monitoring and feedback loops",
        key_deliverables=["Production deployment", "Feedback system", "Performance dashboard"],
        success_criteria=["<5% error rate", "User feedback collected", "Alerts configured"]
    ),
    "optimization": RoadmapPhase(
        name="Optimization & Scale",
        duration_months=3,
        description="Iterate based on production data, scale capabilities",
        key_deliverables=["Model updates", "Feature enhancements", "Scalability improvements"],
        success_criteria=["Improved metrics", "Cost optimization", "New use cases identified"]
    )
}

def create_roadmap(product_name: str, vision: str, start_date: str, selected_phases: List[str]) -> AIRoadmap:
    """Create an AI product roadmap from selected phases."""
    phases = []
    current_month = 1
    
    for phase_key in selected_phases:
        if phase_key in PHASE_TEMPLATES:
            template = PHASE_TEMPLATES[phase_key]
            phase = RoadmapPhase(
                name=template.name,
                start_month=current_month,
                duration_months=template.duration_months,
                description=template.description,
                key_deliverables=template.key_deliverables,
                success_criteria=template.success_criteria
            )
            phases.append(phase)
            current_month += template.duration_months
    
    return AIRoadmap(product_name=product_name, vision=vision, phases=phases)

def print_roadmap(roadmap: AIRoadmap):
    """Print a formatted roadmap to console."""
    print(f"\n{'='*60}")
    print(f"AI PRODUCT ROADMAP: {roadmap.product_name}")
    print(f"{'='*60}")
    print(f"\nVision: {roadmap.vision}\n")
    print(f"{'PHASE':<30} {'Duration':<15} {'Deliverables'}")
    print(f"{'-'*60}")
    
    for phase in roadmap.phases:
        end_month = phase.start_month + phase.duration_months - 1
        duration = f"M{phase.start_month}-M{end_month}"
        print(f"\n{phase.name:<30} {duration:<15}")
        print(f"  Description: {phase.description}")
        print(f"  Key Deliverables:")
        for d in phase.key_deliverables:
            print(f"    - {d}")
        print(f"  Success Criteria:")
        for s in phase.success_criteria:
            print(f"    - {s}")
    
    print(f"\n{'='*60}")
    print("Generated by KateelLearningDemos")
    print("Attribution: vinallcontact@gmail.com")

def main():
    print("\n" + "="*50)
    print("AI Product Roadmap Planner")
    print("="*50)
    
    product_name = input("\nProduct Name: ").strip() or "AI Project"
    vision = input("Vision Statement: ").strip() or "Build an AI solution that creates value"
    start_date = input("Start Date (YYYY-MM-DD): ").strip() or datetime.now().strftime("%Y-%m-%d")
    
    print("\nAvailable Phases:")
    for i, key in enumerate(PHASE_TEMPLATES.keys(), 1):
        print(f"  {i}. {PHASE_TEMPLATES[key].name}")
    
    print("\nEnter phase numbers (comma-separated, e.g., '1,2,3'):")
    selection = input("> ").strip()
    
    phase_keys = list(PHASE_TEMPLATES.keys())
    selected_phases = []
    for s in selection.split(','):
        try:
            idx = int(s.strip()) - 1
            if 0 <= idx < len(phase_keys):
                selected_phases.append(phase_keys[idx])
        except ValueError:
            pass
    
    if not selected_phases:
        selected_phases = list(phase_keys)
    
    roadmap = create_roadmap(product_name, vision, start_date, selected_phases)
    print_roadmap(roadmap)
    
    # Save to file
    with open(f"{product_name.replace(' ', '_')}_roadmap.json", 'w') as f:
        json.dump(roadmap.to_dict(), f, indent=2)
    print(f"\nRoadmap saved to {product_name.replace(' ', '_')}_roadmap.json")

if __name__ == "__main__":
    main()