// Pre-computed synthetic incident results. Generated by a private build tool; no calculation source ships with this page.
const CIR_DATA = {
 "cve": {
  "cve_id": "CVE-2026-77777",
  "package": "jollyhttp",
  "affected_below_version": "4.2.8",
  "fixed_version": "4.2.8",
  "cvss": 9.8,
  "exploit_in_wild": true,
  "published_utc": "2026-08-31T20:40:00",
  "description": "Unauthenticated remote code execution via crafted multipart upload path in JollyHTTP < 4.2.8 (fictional)."
 },
 "detected_at": "2026-09-01 07:40:00",
 "totals": {
  "assets_vulnerable": 7,
  "assets_attempted": 2,
  "assets_compromised": 1,
  "pii_records_at_risk": 182000,
  "response_cost": 3110000.0,
  "all_patched_by": "2026-09-01 23:40:00",
  "hours_to_all_clear": 16.0
 },
 "radius": [
  {
   "host": "dealer-portal-01",
   "service": "Dealer portal (orders, credits, PII)",
   "env": "prod",
   "internet": true,
   "version": "4.1.9",
   "status": "likely_compromised",
   "score": 19,
   "hits": 14,
   "successes": 5
  },
  {
   "host": "b2b-api-01",
   "service": "B2B order API (OEM EDI bridge)",
   "env": "prod",
   "internet": true,
   "version": "4.2.1",
   "status": "attempted",
   "score": 15,
   "hits": 9,
   "successes": 0
  },
  {
   "host": "vendor-portal-01",
   "service": "Supplier collaboration portal",
   "env": "prod",
   "internet": true,
   "version": "4.1.2",
   "status": "attempted",
   "score": 13,
   "hits": 6,
   "successes": 0
  },
  {
   "host": "hr-portal-01",
   "service": "Employee self-service portal",
   "env": "prod",
   "internet": false,
   "version": "3.9.4",
   "status": "vulnerable",
   "score": 6,
   "hits": 0,
   "successes": 0
  },
  {
   "host": "intranet-01",
   "service": "Corporate intranet",
   "env": "prod",
   "internet": false,
   "version": "4.0.2",
   "status": "vulnerable",
   "score": 4,
   "hits": 0,
   "successes": 0
  },
  {
   "host": "b2b-api-stg",
   "service": "B2B API (staging)",
   "env": "staging",
   "internet": false,
   "version": "4.2.1",
   "status": "vulnerable",
   "score": 2,
   "hits": 0,
   "successes": 0
  },
  {
   "host": "dealer-portal-stg",
   "service": "Dealer portal (staging)",
   "env": "staging",
   "internet": false,
   "version": "4.1.9",
   "status": "vulnerable",
   "score": 2,
   "hits": 0,
   "successes": 0
  }
 ],
 "events": [
  {
   "time": "2026-08-31 22:40:24.260626",
   "host": "A02",
   "src": "198.51.100.87",
   "path": "/jolly/upload;.jsp",
   "status": 403
  },
  {
   "time": "2026-08-31 23:00:17.015072",
   "host": "A09",
   "src": "192.0.2.146",
   "path": "/jolly/upload;.jsp",
   "status": 403
  },
  {
   "time": "2026-08-31 23:12:56.694520",
   "host": "A01",
   "src": "198.51.100.87",
   "path": "/jolly/upload;.jsp",
   "status": 403
  },
  {
   "time": "2026-08-31 23:13:30.309115",
   "host": "A01",
   "src": "198.51.100.87",
   "path": "/jolly/upload;.jsp",
   "status": 403
  },
  {
   "time": "2026-08-31 23:18:19.725918",
   "host": "A09",
   "src": "198.51.100.87",
   "path": "/jolly/upload;.jsp",
   "status": 403
  },
  {
   "time": "2026-08-31 23:19:57.835648",
   "host": "A02",
   "src": "192.0.2.146",
   "path": "/jolly/upload;.jsp",
   "status": 403
  },
  {
   "time": "2026-08-31 23:30:11.145125",
   "host": "A01",
   "src": "192.0.2.146",
   "path": "/jolly/upload;.jsp",
   "status": 403
  },
  {
   "time": "2026-08-31 23:35:55.768830",
   "host": "A01",
   "src": "198.51.100.87",
   "path": "/jolly/upload;.jsp",
   "status": 403
  },
  {
   "time": "2026-08-31 23:39:14.977302",
   "host": "A01",
   "src": "198.51.100.23",
   "path": "/jolly/upload;.jsp",
   "status": 403
  },
  {
   "time": "2026-09-01 00:38:57.418368",
   "host": "A02",
   "src": "198.51.100.87",
   "path": "/jolly/upload;.jsp",
   "status": 403
  },
  {
   "time": "2026-09-01 00:53:31.948035",
   "host": "A09",
   "src": "192.0.2.146",
   "path": "/jolly/upload;.jsp",
   "status": 403
  },
  {
   "time": "2026-09-01 01:05:06.459967",
   "host": "A01",
   "src": "198.51.100.23",
   "path": "/jolly/upload;.jsp",
   "status": 403
  },
  {
   "time": "2026-09-01 01:28:00",
   "host": "A01",
   "src": "198.51.100.23",
   "path": "/jolly/upload;.jsp",
   "status": 200
  },
  {
   "time": "2026-09-01 01:38:32.525645",
   "host": "A01",
   "src": "198.51.100.23",
   "path": "/jolly/upload;.jsp",
   "status": 403
  },
  {
   "time": "2026-09-01 01:46:00",
   "host": "A01",
   "src": "198.51.100.23",
   "path": "/jolly/upload;.jsp",
   "status": 200
  },
  {
   "time": "2026-09-01 02:04:00",
   "host": "A01",
   "src": "198.51.100.23",
   "path": "/jolly/tmp/.cache.jsp",
   "status": 200
  },
  {
   "time": "2026-09-01 02:19:11.279294",
   "host": "A01",
   "src": "192.0.2.146",
   "path": "/jolly/upload;.jsp",
   "status": 403
  },
  {
   "time": "2026-09-01 02:37:21.659129",
   "host": "A01",
   "src": "198.51.100.23",
   "path": "/jolly/upload;.jsp",
   "status": 403
  },
  {
   "time": "2026-09-01 02:48:44.171605",
   "host": "A02",
   "src": "198.51.100.23",
   "path": "/jolly/upload;.jsp",
   "status": 403
  },
  {
   "time": "2026-09-01 02:52:32.769393",
   "host": "A02",
   "src": "198.51.100.87",
   "path": "/jolly/upload;.jsp",
   "status": 403
  },
  {
   "time": "2026-09-01 03:34:00",
   "host": "A01",
   "src": "198.51.100.23",
   "path": "/jolly/tmp/.cache.jsp",
   "status": 200
  },
  {
   "time": "2026-09-01 04:18:52.377080",
   "host": "A02",
   "src": "192.0.2.146",
   "path": "/jolly/upload;.jsp",
   "status": 403
  },
  {
   "time": "2026-09-01 04:29:14.350217",
   "host": "A02",
   "src": "198.51.100.87",
   "path": "/jolly/upload;.jsp",
   "status": 403
  },
  {
   "time": "2026-09-01 04:44:12.230088",
   "host": "A09",
   "src": "198.51.100.87",
   "path": "/jolly/upload;.jsp",
   "status": 403
  },
  {
   "time": "2026-09-01 04:47:30.815527",
   "host": "A09",
   "src": "192.0.2.146",
   "path": "/jolly/upload;.jsp",
   "status": 403
  },
  {
   "time": "2026-09-01 05:01:41.270119",
   "host": "A09",
   "src": "198.51.100.23",
   "path": "/jolly/upload;.jsp",
   "status": 403
  },
  {
   "time": "2026-09-01 05:18:52.880728",
   "host": "A02",
   "src": "198.51.100.23",
   "path": "/jolly/upload;.jsp",
   "status": 403
  },
  {
   "time": "2026-09-01 05:22:00",
   "host": "A01",
   "src": "198.51.100.23",
   "path": "/jolly/tmp/.cache.jsp",
   "status": 200
  },
  {
   "time": "2026-09-01 05:44:14.956041",
   "host": "A02",
   "src": "192.0.2.146",
   "path": "/jolly/upload;.jsp",
   "status": 403
  }
 ],
 "plan": [
  {
   "host": "dealer-portal-01",
   "action": "ISOLATE now + forensic image + patch & rebuild",
   "start": 0.0,
   "hours": 7.0,
   "cost": 2450000.0,
   "approval": "YES \u2014 production isolation (COO/CIO)"
  },
  {
   "host": "b2b-api-01",
   "action": "Patch jollyhttp 4.2.1 -> 4.2.8",
   "start": 7.0,
   "hours": 3.0,
   "cost": 420000.0,
   "approval": "YES \u2014 prod window (service owner)"
  },
  {
   "host": "vendor-portal-01",
   "action": "Patch jollyhttp 4.1.2 -> 4.2.8",
   "start": 7.0,
   "hours": 3.0,
   "cost": 150000.0,
   "approval": "YES \u2014 prod window (service owner)"
  },
  {
   "host": "hr-portal-01",
   "action": "Patch jollyhttp 3.9.4 -> 4.2.8",
   "start": 10.0,
   "hours": 3.0,
   "cost": 60000.0,
   "approval": "YES \u2014 prod window (service owner)"
  },
  {
   "host": "intranet-01",
   "action": "Patch jollyhttp 4.0.2 -> 4.2.8",
   "start": 10.0,
   "hours": 3.0,
   "cost": 30000.0,
   "approval": "YES \u2014 prod window (service owner)"
  },
  {
   "host": "b2b-api-stg",
   "action": "Patch jollyhttp 4.2.1 -> 4.2.8",
   "start": 13.0,
   "hours": 3.0,
   "cost": 0.0,
   "approval": "no"
  },
  {
   "host": "dealer-portal-stg",
   "action": "Patch jollyhttp 4.1.9 -> 4.2.8",
   "start": 13.0,
   "hours": 3.0,
   "cost": 0.0,
   "approval": "no"
  }
 ],
 "clock": [
  {
   "obligation": "CERT-In incident report (CERT-In directions, 2022)",
   "trigger": "Cyber incident of a mandatory-reporting class detected",
   "deadline": "2026-09-01 13:40:00",
   "owner": "CISO + Legal",
   "status": "REQUIRED"
  },
  {
   "obligation": "DPDP Act breach notification (Data Protection Board + data principals)",
   "trigger": "Personal data likely accessed (182,000 records)",
   "deadline": "2026-09-04 07:40:00",
   "owner": "DPO + Legal",
   "status": "PREPARE"
  },
  {
   "obligation": "OEM customer contractual security notice",
   "trigger": "B2B API attempted-intrusion (blocked); several OEM contracts require notice of material incidents",
   "deadline": "2026-09-03 07:40:00",
   "owner": "Sales head + Legal",
   "status": "ASSESS"
  }
 ],
 "notice": "Everything here is fictional \u2014 the CVE, the software, all hosts and IPs (TEST-NET ranges). Synthetic, pre-computed data; this simulation makes no network calls."
};
