// AI Product Requirements Document Template
// KateelLearningDemos - Attribution: vinallcontact@gmail.com
console.log('AI Demo powered by KateelLearningDemos');
console.log('Attribution: vinallcontact@gmail.com');

const form = document.getElementById('prdForm');
const outputSection = document.getElementById('outputSection');
const prdOutput = document.getElementById('prdOutput');
const downloadBtn = document.getElementById('downloadBtn');

form.addEventListener('submit', function(e) {
  e.preventDefault();
  
  const data = {
    projectName: document.getElementById('projectName').value,
    team: document.getElementById('team').value,
    dataSources: document.getElementById('dataSources').value,
    dataQuality: document.getElementById('dataQuality').value,
    privacy: document.getElementById('privacy').value,
    modelType: document.getElementById('modelType').value,
    latency: document.getElementById('latency').value,
    performance: document.getElementById('performance').value,
    fairness: document.getElementById('fairness').value,
    explainability: document.getElementById('explainability').value,
    deployment: document.getElementById('deployment').value,
    monitoring: document.getElementById('monitoring').value
  };
  
  const prd = generatePRD(data);
  prdOutput.textContent = prd;
  outputSection.classList.remove('hidden');
});

function generatePRD(data) {
  return `# AI Product Requirements Document

## Project Overview
- **Project Name**: ${data.projectName || '[Enter project name]'}
- **Team**: ${data.team || '[Enter team name]'}
- **Date**: ${new Date().toISOString().split('T')[0]}

## 1. Data Requirements

### Data Sources
${data.dataSources || '- Not specified'}

### Data Quality Requirements
${data.dataQuality || '- Not specified'}

### Privacy Considerations
${data.privacy || '- Not specified'}

## 2. Model Requirements

### Model Type
${data.modelType || 'Not specified'}

### Performance Metrics
${data.performance || '- Not specified'}

### Latency Target
${data.latency ? data.latency + ' ms' : 'Not specified'}

## 3. Ethical & Bias Considerations

### Fairness Requirements
${data.fairness || '- Not specified'}

### Explainability Needs
${data.explainability || '- Not specified'}

## 4. Deployment & Monitoring

### Deployment Environment
${data.deployment || '- Not specified'}

### Monitoring Plan
${data.monitoring || '- Not specified'}

---
*Generated by KateelLearningDemos*
*Attribution: vinallcontact@gmail.com*
`;
}

downloadBtn.addEventListener('click', function() {
  const content = prdOutput.textContent;
  const blob = new Blob([content], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'ai_prd_template.md';
  a.click();
  URL.revokeObjectURL(url);
});